#first db
multi-datasource:
  datasource-ledger-sync:
    hikari-config:
        jdbc-url: jdbc:postgresql://${LEDGER_SYNC_HOST:10.4.10.112}:${LEDGER_SYNC_PORT:54333}/${LEDGER_SYNC_DB:ledger_sync}
        username: ${LEDGER_SYNC_USER_NAME:verifier_read}
        password: ${LEDGER_SYNC_PASSWORD:verifier_read}
        driver-class-name: org.postgresql.Driver
        schema: ${LEDGER_SYNC_SCHEMA:mainnet}
  datasource-db-sync:
    hikari-config:
      jdbc-url: jdbc:postgresql://${DB_SYNC_HOST:10.4.10.231}:${DB_SYNC_PORT:5434}/${DB_SYNC_DB:cardano_mainnet}
      username: ${DB_SYNC_USER_NAME:cardano_mainnet_read}
      password: ${DB_SYNC_PASSWORD:1}
      driver-class-name: org.postgresql.Driver
      schema: ${DB_SYNC_SCHEMA:public}
amount:
  ada_pots:
    amount_ada_pots: 1000
spring:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true


