flowchart TD
    A["Start"] --> B1{"Do you know what application you want to develop?"}
    B1 -- Yes --> C1["Yes, I know what I want to build"]
    B1 -- No --> C2@{ label: "No, I'm exploring" }
    B1 -- Not sure --> C3["I have an idea and want to focus on coding"]
    C2 --> AA1["Visit our blueprint examples"]
    C3 --> H1["java"]
    C1 --> D1{"How is your solution designed to access blockchain data?"}
    D1 --> E1["Through a ready to use sandbox cloud environment (BaaS)"] & E2["Simply calling APIs."] & E3["Serverless or client-side application, using off-chain libraries / SDKs and their embedded data providers."] & E4["Hosting my own infrastructure and chain indexer solution"]
    E1 --> H1
    E2 --> PO["Blockfrost"] & P1["Apollo"] & P2["go-cardano-serialization"]
    E3 --> F1{"What language are you proficient in?"}
    F1 --> G1["Haskell"] & G2["Rust"] & G3["Java"] & G4["JavaScript, TypeScript"] & G5["Python"] & G6["Go"] & G7["ELM"] & G8[".NET, C#"] & G9["C"] & G10["Elixir"] & G11["Kotlin"]
    G1 --> Q1["ELM Cardano"] & Q2["Kuber"] & Q3["UTxO RPC Haskell-SDK"]
    G2 --> L1["Cardano Serialization Lib"] & L2["Cardano Multiplatform Lib"] & L3["Oura"] & L4["Pallas"] & L5["Pallas.NET"] & L6["Wisky"] & L7["UTxO RPC Rust-SDK"]
    G3 --> M1["Cardano Client Lib (CCL)"] & M2["Koios Java Client"] & M3["Ogmios Java Client"] & M4["Yaci Store"] & M5["cf-java-rewards-calculation"]
    G4 --> N1["MeshJS or Mesh SDK"] & N2["Lucid"] & N3["Lucid Evolution"] & N4["Blaze-Cardano"] & N5["Plu-ts"] & N6["Cardano-JS-SDK"] & N7["TyphonJS"] & N8["Cardano Web3.js"] & N9["Buildooor"] & N10["UTxO RPC Web-SDK"]
    G5 --> O1["Koios Python"] & O2["PyCardano"] & O3["Automint"] & O4["Koios Python"] & O5["NFT Vending Machine"] & O6["UTxO RPC Python-SDK"]
    G6 --> P1 & P2 & P3["Cardano Node API"] & P4["UTxO RPC Go SDK"]
    G7 --> Q1
    G8 --> R1["Argus"] & R2["CardanoSharp Wallet"] & R3["Pallas.NET"] & R4["UTxO RPC donet-SDK"]
    G9 --> S1["Cardano-C"] & S2["libCardano"]
    G10 --> T1["Xogmios"]
    G11 --> U1["Kogmios"]
    E4 --> BB1{"Does your application requires just live data or historical data too?"}
    BB1 -- Live Data --> AB1["Solutions"]
    AB1 --> AG1["Native Cardano Node libraries and APIs"] & AJ1["Ogmios - Haskell"] & AJ2["Oura - Rust"] & AJ3["UTxO-RPC - Rust"] & AJ4["Adder - Go"] & AJ5["Yaci - Java"]
    AG1 --> AH1["Cardano Node API"] & AH2["Cardano CLI"]
    AH1 --> CardanoNodeApiCodeExample@{ label: "# Cardano Node API Example\n~~~go\n// Start API listener\n\tgo func() {\n\t\tif err := api.Start(cfg); err != nil {\n\t\t\tlogger.Error('failed to start API:', 'error', err)\n\t\t\tos.Exit(1)\n\t\t}\n\t}()\n~~~" }
    BB1 -- Historical Data --> AB2{"What features do you need?"}
    AB2 --> AB3["Data Completeness - Ledger State"] & AB4["Data API Acess"] & AB5["Lightweight"] & AB6["Selective / Custom / Scope Indexing"] & AB7["Aggregated data"] & AB8["Cardano data in CBOR format"] & AB9["Modular architecture"] & AB10["Fast Sync"] & AB11["Scalable"] & AB12["Docker availability"] & AB13["Database technology"] & AB14["Streaming Technology"]
    AB3 --> AD1["Cardano DB-Sync"] & AD2["Yaci Store"]
    AB4 --> AD3["Yaci Store - REST"] & AD4["Carp - REST"] & AD5["Kupo - REST"] & AD6["Cardano GraphQL - GraphQL"]
    AB5 --> AD7["Kupo"] & AD8["Yaci Store"] & AD9["Carp"]
    AB6 --> AD10["Yaci Store"] & AD11["DB-Sync"] & AD12["Carp"] & AD13["Kupo"] & AD14["Mafoc"]
    AB7 --> AD15["Scrolls"] & AD16["Yaci Store"]
    AB8 --> AD17["Mumak"]
    AB9 --> AD18["Yaci Store"] & AD19["Carp"]
    AB10 --> AD20["Yaci Store"] & AD21["Carp"] & AD22["DB-Sync"]
    AB11 --> AD23["DB-Sync"] & AD24["Yaci Store"] & AD25["Kupo"] & AD26["Scrolls"] & AD27["Carp"]
    AB12 --> AD28["Yaci Store"] & AD29["DB-Sync"] & AD30["Carp"] & AD31["Kupo"] & AD32["Ogmios"] & AD33["Scrolls"] & AD34["Oura"] & AD35["Mumak"]
    AB13 --> AD36["PotgresSQL"] & AD37["MySQL"] & AD38["SQLite"] & AD39["H2"] & AD40["Redis"]
    AD36 --> AE1["DB-Sync"] & AE2["Yaci Store"] & AE3["Mumak"] & AE4["Carp"]
    AD37 --> AE5["Yaci Store"]
    AD38 --> AE6["Kupo"]
    AD39 --> AE7["Yaci Store"]
    AD40 --> AE8["Scrolls"]
    AB14 --> AE9["Spring Boots"]
    AE9 --> AF1["Yaci Store"]
    n1["Triangle"]
    n2["Hexagon"]
    n3["Filled Circle"]

    C2@{ shape: rect}
    CardanoNodeApiCodeExample@{ shape: rect}
    n1@{ shape: tri}
    n2@{ shape: hex}
    n3@{ shape: f-circ}
    click H1 "storage/java"
    click P1 "https://github.com/Salvionied/apollo"
    click P2 "https://github.com/fivebinaries/go-cardano-serialization"
    click Q1 "https://github.com/elm-cardano/elm-cardano"
    click Q2 "https://github.com/dQuadrant/kuber"
    click Q3 "https://github.com/utxorpc/haskell-sdk"
    click L1 "https://github.com/Emurgo/cardano-serialization-lib"
    click L2 "https://github.com/dcSpark/cardano-multiplatform-lib#cardano-multiplatform-lib"
    click L3 "https://oura.txpipe.io/v2"
    click L4 "https://github.com/txpipe/pallas"
    click L5 "https://github.com/SAIB-Inc/Pallas.NET"
    click L6 "https://github.com/sidan-lab/whisky"
    click L7 "https://github.com/utxorpc/rust-sdk"
    click M1 "https://github.com/bloxbean/cardano-client-lib"
    click M2 "https://github.com/cardano-community/koios-java-client"
    click M3 "https://github.com/adabox-aio/ogmios-java-client"
    click M4 "https://github.com/bloxbean/yaci-store"
    click M5 "https://github.com/cardano-foundation/cf-java-rewards-calculation"
    click N1 "https://meshjs.dev/"
    click N2 "https://github.com/spacebudz/lucid"
    click N3 "https://github.com/Anastasia-Labs/lucid-evolution"
    click N4 "https://github.com/butaneprotocol/blaze-cardano"
    click N5 "https://github.com/HarmonicLabs/plu-ts"
    click N6 "https://github.com/input-output-hk/cardano-js-sdk"
    click N7 "https://github.com/StricaHQ/typhonjs"
    click N8 "https://github.com/xray-network/cardano-web3-js"
    click N9 "https://github.com/HarmonicLabs/buildooor"
    click N10 "https://github.com/utxorpc/web-sdk"
    click O1 "https://github.com/cardano-community/koios-python"
    click O2 "https://github.com/cffls/pycardano"
    click O3 "https://github.com/creativequotient/automint"
    click O4 "https://github.com/cardano-community/koios-python"
    click O5 "https://github.com/thaddeusdiamond/cardano-nft-vending-machine"
    click O6 "https://github.com/utxorpc/python-sdk"
    click P3 "https://github.com/blinklabs-io/cardano-node-api"
    click P4 "https://github.com/utxorpc/go-sdk"
    click R1 "https://github.com/SAIB-Inc/Argus"
    click R2 "https://github.com/CardanoSharp/cardanosharp-wallet"
    click R3 "https://github.com/SAIB-Inc/Pallas.NET"
    click R4 "https://github.com/utxorpc/dotnet-sdk"
    click S1 "https://github.com/Biglup/cardano-c"
    click S2 "https://gitlab.com/viperscience/libcardano"
    click T1 "https://github.com/wowica/xogmios"
    click U1 "https://github.com/projectNEWM/kogmios"
    click AJ1 "https://github.com/CardanoSolutions/ogmios"
    click AJ2 "https://github.com/txpipe/oura"
    click AJ3 "https://utxorpc.org/cardano"
    click AJ4 "https://github.com/blinklabs-io/adder"
    click AJ5 "https://github.com/bloxbean/yaci"
    click AH2 "https://github.com/IntersectMBO/cardano-cli"
    click AD1 "https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/schema.md"
    click AD2 "https://store.yaci.xyz/"
    click AD3 "https://github.com/bloxbean/yaci-store/tree/main/stores-api"
    click AD4 "https://github.com/dcSpark/carp/blob/main/docs/bin/openapi.json"
    click AD5 "https://cardanosolutions.github.io/kupo/#tag/Matches"
    click AD6 "https://github.com/cardano-foundation/cardano-graphql"
    click AD7 "https://github.com/CardanoSolutions/kupo"
    click AD8 "https://store.yaci.xyz/"
    click AD9 "https://dcspark.github.io/carp/docs/requirements"
    click AD10 "https://github.com/bloxbean/yaci-store/tree/main/stores"
    click AD11 "https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/configuration.md"
    click AD12 "https://dcspark.github.io/carp/docs/indexer/Tasks/"
    click AD13 "https://github.com/CardanoSolutions/kupo/blob/master/src/Kupo/Data/Pattern.hs"
    click AD14 "https://github.com/eyeinsky/mafoc"
    click AD15 "https://github.com/txpipe/scrolls"
    click AD16 "https://store.yaci.xyz/usage/aggregation-app-getting-started"
    click AD17 "https://github.com/txpipe/mumak"
    click AD18 "https://store.yaci.xyz/"
    click AD19 "https://dcspark.github.io/carp/docs/intro"
    click AD20 "https://store.yaci.xyz/"
    click AD21 "https://github.com/dcSpark/carp"
    click AD22 "https://github.com/IntersectMBO/cardano-db-sync/tree/master/doc"
    click AD23 "https://github.com/IntersectMBO/cardano-db-sync/tree/master/doc"
    click AD24 "https://store.yaci.xyz/"
    click AD25 "https://github.com/CardanoSolutions/kupo"
    click AD26 "https://github.com/txpipe/scrolls"
    click AD27 "https://github.com/dcSpark/carp/"
    click AD28 "https://github.com/bloxbean/yaci-store/tree/main/docker"
    click AD29 "https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/docker.md"
    click AD30 "https://dcspark.github.io/carp/docs/indexer/docker"
    click AD31 "https://hub.docker.com/r/cardanosolutions/kupo"
    click AD32 "https://hub.docker.com/r/cardanosolutions/ogmios"
    click AD33 "https://github.com/txpipe/scrolls/blob/main/testdrive/simple/docker-compose.yml"
    click AD34 "https://txpipe.github.io/oura/installation/docker.html"
    click AD35 "https://github.com/txpipe/mumak/tree/main/docker"
    click AE1 "https://github.com/IntersectMBO/cardano-db-sync"
    click AE2 "https://github.com/bloxbean/yaci-store"
    click AE3 "https://github.com/txpipe/mumak"
    click AE4 "https://github.com/dcSpark/carp/"
    click AE5 "https://store.yaci.xyz/"
    click AE6 "https://github.com/CardanoSolutions/kupo"
    click AE7 "https://store.yaci.xyz/"
    click AE8 "https://github.com/txpipe/scrolls"
    click AF1 "https://store.yaci.xyz/design"


