flowchart TD
    A["Start"] --> B1{"Do you know what application you want to develop?"}
    B1 -- Yes --> C1["Yes, I know what I want to build"]
    B1 -- No --> C2@{ label: "No, I'm exploring" }
    B1 -- Not sure --> C3["I have an idea and want to focus on coding"]
    C3 --> H1["java"]
    C1 --> D1{"How is your solution designed to access blockchain data?"}
    D1 --> E1["Through a ready to use sandbox cloud environment (BaaS)"] & E2["Simply calling APIs."]
    E1 --> H1
    E2 --> P1["Apollo"]

    C2@{ shape: rect}
    click C2 "https://github.com/"
    click H1 "java"
    click P1 "simplyCallingAPI"


