spring:
  # Datasource specific configs
  datasource:
    # Hikari specific configs
    hikari:
      pool-name: explorer-consumer-pool
      minimum-idle: ${HIKARI_MINIMUM_IDLE:10} #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:48} #maximum pool size
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:300000} #maximum idle time for connection
      max-lifetime: ${HIKARI_MAX_LIFETIME:900000} #maximum lifetime in milliseconds of a connection in the pool after it is closed.
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:50000} #maximum number of milliseconds that a client will wait for a connection
      auto-commit: ${HIKARI_AUTO_COMMIT:true} #default auto-commit behavior.
      connection-init-sql: SELECT 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  # JPA specific configs
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 1000
        show_sql: false
        format_sql: true
        order_inserts: true
        order_updates: true
        hbm2ddl:
          auto: none
  ## Flyway config
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    group: true
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    locations:
      - classpath:db/migration/ledgersync
      - classpath:db/store/{vendor}
    validate-on-migrate: ${FLYWAY_VALIDATE:false}
    create-schemas: ${ALLOW_CREATE_SCHEMA:true}
    out-of-order: true
  codec:
    max-in-memory-size: 10MB
#      props: |
#        max.poll.records: 10
#        fetch.min.bytes: 123456
#    prefix: "explorer-consumer-local"
logging:
  level:
    org.cardanofoundation: ${LOG:INFO}

blocks:
  batch-size: ${BLOCKS_BATCH_SIZE:100}
  commitThreshold: ${COMMIT_THRESHOLD:3000}

genesis:
  byron: ${BYRON_GENESIS_URL:classpath:networks/${NETWORK}/byron-genesis.json}
  shelley: ${SHELLEY_GENESIS_URL:classpath:networks/${NETWORK}/shelley-genesis.json}
  alonzo: ${ALONZO_GENESIS_URL:classpath:networks/${NETWORK}/alonzo-genesis.json}
  conway: ${CONWAY_GENESIS_URL:classpath:networks/${NETWORK}/conway-genesis.json}
  config: ${GENESIS_CONFIG_URL:classpath:networks/${NETWORK}/config.json}
store:
  cardano:
    byron-genesis-file: classpath:networks/${NETWORK}/byron-genesis.json
    shelley-genesis-file: classpath:networks/${NETWORK}/shelley-genesis.json
    keep-alive-interval: ${STORE_CARDANO_KEEP_ALIVE_INTERVAL:10000}
ledger-sync:
  scheduler:
    pool-offline-data:
      fixed-delay: ${POOL_OFFLINE_DATA_FIXED_DELAY:172800}
      initial-delay: ${POOL_OFFLINE_DATA_INIT_DELAY:20000}
    enabled: ${SCHEDULER_ENABLED:true}
  healthcheck:
    enabled: ${HEALTH_CHECK_ENABLED:true}
    event-time-threshold: ${EVENT_TIME_THRESHOLD_IN_SECOND:900}
    block-time-check-enabled: ${BLOCK_TIME_CHECK_ENABLED:true}
    block-time-threshold: ${BLOCK_TIME_THRESHOLD_IN_SECOND:180}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,prometheus,health-status"
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
    health-status:
      enabled: ${HEALTH_CHECK_ENABLED:true}
