replicaCount: 1

tolerations: null
affinity: null

useLocalCardanoNode: false
localCardanoNode:
  enabled: false
  image:
    repository: ghcr.io/blinklabs-io/cardano-node
    tag: 8.9.0-1-amd64
  mithrilRestore: "true"
  tolerations: null
  affinity: null

image:
  repository: cardanofoundation/cf-ledger-sync
  tag: "d5f1455"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

monitoringEnabled: true

diagnosticMode:
  enabled: false

# batching
blocks:
  batchSize: "100"
  commitThreshold: "3000"

dbSchema: public

aggregation:
  enabled: false
  image:
    repository: cardanofoundation/cf-ledger-sync-aggregation
    tag: "7b05530"
    pullPolicy: Always
  dbSchema: public
  store:
    account:
      history_cleanup_enabled: "true"
  resources: {}
