replicaCount: 1

tolerations: null
affinity: null

useLocalCardanoNode: false
localCardanoNode:
  enabled: false
  image:
    repository: ghcr.io/blinklabs-io/cardano-node
    tag: 8.9.0-1-amd64
  mithrilRestore: "true"
  tolerations: null
  affinity: null

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

monitoringEnabled: true

diagnosticMode:
  enabled: false

# batching
blocks:
  batchSize: "100"
  commitThreshold: "3000"

dbSchema: public

indexer:
  enabled: true
  replicaCount: 1
  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-sync"
    tag: "a842354-8831465254"
    pullPolicy: Always
  postgres:
#    dbSchema: public
    secretName: postgres-secrets
    hostKey: POSTGRES_HOST
    portKey: POSTGRES_PORT
    dbKey: LEDGER_SYNC_DB
    userKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 512Mi


aggregation:
  enabled: false
  replicaCount: 1
  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-sync"
    tag: "a842354-8831465254"
    pullPolicy: Always
  postgres:
#    dbSchema: aggregation
    secretName: postgres-secrets
    hostKey: POSTGRES_HOST
    portKey: POSTGRES_PORT
    dbKey: LEDGER_SYNC_DB
    userKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD
  store:
    account:
      history_cleanup_enabled: "true"
    executor:
      # Whether to use parallel processing. This greatly reduces DB computation requirements
      enable_parallel_processing: "true"
      # Whether to use virtual threads. True recommended for multi-CPU architecture, false for VMs
      use_virtual_thread_for_batch_processing: "true"
      use_virtual_thread_for_event_processing: "true"
      # Number of concurrent batching threads
      block_processing_threads: 15
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 512Mi
