version: "3.9"
services:
  cf-ledger-sync-streamer:
    image: pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-sync-streamer:162724a
    container_name: ledger-sync-streamer
    environment:
      - STORE_CARDANO_HOST=preprod-node.world.dev.cardano.org
      - STORE_CARDANO_PORT=30000
      - STORE_CARDANO_PROTOCOL-MAGIC=1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/streamer
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
      - SCHEMA=streamer
      - STORE_REMOTE_PUBLISHER-ENABLED=true
      - scs_binder=rabbit
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - STORE_REMOTE_PUBLISHER-EVENTS=byronMainBlockEvent,byronEbBlockEvent,blockEvent,rollbackEvent
    # - STORE_CARDANO_SYNC-START-SLOT=29883443
    # - STORE_CARDANO_SYNC-START-BLOCKHASH=e78c93b9eb2bd312c49f464cf2aa0564405f3ab1408f525c6f3ada5b1c43992b

    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: on-failure
    networks:
      - ledger-sync-net

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    restart: on-failure
    networks:
      - ledger-sync-net

  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:13.2
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=streamer
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - ledger-sync-net
volumes:
  postgres-data:
  rabbitmq-data:

networks:
  ledger-sync-net:
    driver: bridge
