spring:
  banner:
    location: classpath:/banner.txt

  jpa:
    properties:
      hibernate:
        default_schema: ${SCHEMA}

  flyway:
    locations: classpath:db/store/{vendor}
    out-of-order: true
    schemas: ${SCHEMA}

  logging:

    file:
      name: ./logs/ledger-sync-streamer.log

  cloud:
    stream:
      kafka:
        binder:
          producer-properties:
            max.request.size: 200000000

streamer:
  healthcheck:
    published-time-threshold: ${PUBLISHED_TIME_THRESHOLD_IN_SECOND:120}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,prometheus,health-status"
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
    health-status:
      enabled: true
