spring:
  banner:
    location: classpath:/banner.txt

  flyway:
    locations: classpath:db/store/{vendor}
    out-of-order: true

  logging:

    file:
      name: ./logs/ledger-sync-streamer.log

  cloud:
    stream:
      kafka:
        binder:
          producer-properties:
            max.request.size: 200000000
      default-binder: ${scs_binder}

ledger-sync:
  healthcheck:
    enabled: ${HEALTH_CHECK_ENABLED:true}
    event-time-threshold: ${EVENT_TIME_THRESHOLD_IN_SECOND:300}
    block-time-check-enabled: ${BLOCK_TIME_CHECK_ENABLED:false}
    block-time-threshold: ${BLOCK_TIME_THRESHOLD_IN_SECOND:180}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,prometheus,health-status"
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
    health-status:
      enabled: ${HEALTH_CHECK_ENABLED:true}
