[libraries]
yaci-store-starter="com.bloxbean.cardano:yaci-store-spring-boot-starter:0.0.12-beta4.5-SNAPSHOT"
yaci-store-utxo-starter="com.bloxbean.cardano:yaci-store-utxo-spring-boot-starter:0.0.12-beta4.5-SNAPSHOT"
yaci-store-account-starter="com.bloxbean.cardano:yaci-store-account-spring-boot-starter:0.0.12-beta4.5-SNAPSHOT"

cardano-client-lib="com.bloxbean.cardano:cardano-client-lib:0.5.0-beta3"
snakeyaml="org.yaml:snakeyaml:2.0"
guava="com.google.guava:guava:32.1.2-jre"
log4j-api="org.apache.logging.log4j:log4j-api:2.20.0"
log4j-core="org.apache.logging.log4j:log4j-core:2.20.0"
jakarta-validation-api="jakarta.validation:jakarta.validation-api:3.0.2"

lombok="org.projectlombok:lombok:1.18.26"
lombok-mapstruct-binding="org.projectlombok:lombok-mapstruct-binding:0.2.0"
map-struct="org.mapstruct:mapstruct:1.5.3.Final"
mapstruct-processor="org.mapstruct:mapstruct-processor:1.5.3.Final"
hibernate-jpamodelgen="org.hibernate:hibernate-jpamodelgen:6.1.7.Final"

cbor="co.nstant.in:cbor:0.9"
bouncycastle-bcprov="org.bouncycastle:bcprov-jdk15on:1.70"
common-codec="commons-codec:commons-codec:1.15"
gson="com.google.code.gson:gson:2.10.1"

embedded-redis="cn.ponfee:embedded-redis:1.2"
pitest="org.pitest:pitest:1.14.2"

