[libraries]
yaci-store-starter="com.bloxbean.cardano:yaci-store-spring-boot-starter:0.0.13-beta2-ac12d37-SNAPSHOT"
yaci-store-remote-starter="com.bloxbean.cardano:yaci-store-remote-spring-boot-starter:0.0.13-beta2-ac12d37-SNAPSHOT"

cardano-client-lib="com.bloxbean.cardano:cardano-client-lib:0.5.0"
snakeyaml="org.yaml:snakeyaml:2.0"
guava="com.google.guava:guava:32.1.2-jre"
log4j-api="org.apache.logging.log4j:log4j-api:2.20.0"
log4j-core="org.apache.logging.log4j:log4j-core:2.20.0"
jakarta-validation-api="jakarta.validation:jakarta.validation-api:3.0.2"

lombok="org.projectlombok:lombok:1.18.30"
lombok-mapstruct-binding="org.projectlombok:lombok-mapstruct-binding:0.2.0"
map-struct="org.mapstruct:mapstruct:1.5.3.Final"
mapstruct-processor="org.mapstruct:mapstruct-processor:1.5.3.Final"
hibernate-jpamodelgen="org.hibernate:hibernate-jpamodelgen:6.1.7.Final"

cbor="co.nstant.in:cbor:0.9"
bouncycastle-bcprov="org.bouncycastle:bcprov-jdk15on:1.70"
common-codec="commons-codec:commons-codec:1.15"
commons-io="commons-io:commons-io:2.11.0"
gson="com.google.code.gson:gson:2.10.1"

embedded-redis="cn.ponfee:embedded-redis:1.2"
pitest="org.pitest:pitest:1.14.2"

junit-engine="org.junit.jupiter:junit-jupiter-engine:5.9.0"
junit-api="org.junit.jupiter:junit-jupiter-api:5.9.0"
assertj-core="org.assertj:assertj-core:3.23.1"

jackson-core="com.fasterxml.jackson.core:jackson-core:2.15.2"
jackson-annotation="com.fasterxml.jackson.core:jackson-annotations:2.15.2"

jgit="org.eclipse.jgit:org.eclipse.jgit:6.5.0.202303070854-r"
javax-api="javax.xml.bind:jaxb-api:2.2.3"
hibernate-types-60="com.vladmihalcea:hibernate-types-60:2.21.1"