version: '3.9'

services:
  ledger-sync-aggregation:
    image: cardanofoundation/cf-ledger-sync-aggregation:0.1.0
    container_name: ledger-sync-aggregation-${NETWORK:-mainnet}
    env_file:
      - .env
      - application.properties
    environment:
      - HEALTH_CHECK_ENABLED=${HEALTH_CHECK_ENABLED:-true}
      - EVENT_TIME_THRESHOLD_IN_SECOND=${EVENT_TIME_THRESHOLD_IN_SECOND:-600}
      - BLOCK_TIME_CHECK_ENABLED=${BLOCK_TIME_CHECK_ENABLED:-true}
      - BLOCK_TIME_THRESHOLD_IN_SECOND=${BLOCK_TIME_THRESHOLD_IN_SECOND:-180}
      - STORE_ACCOUNT_INITIALBALANCESNAPSHOTBLOCK=${STORE_ACCOUNT_INITIALBALANCESNAPSHOTBLOCK:-0}
      - STORE_ACCOUNT_BALANCECALCJOBBATCHSIZE=${STORE_ACCOUNT_BALANCECALCJOBBATCHSIZE:-500}
      - STORE_ACCOUNT_BALANCECALCJOBPARTITIONSIZE=${STORE_ACCOUNT_BALANCECALCJOBPARTITIONSIZE:-5}
      - STORE_ADMIN_HEALTHCHECKINTERVAL=${STORE_ADMIN_HEALTHCHECKINTERVAL:-120}
      - STORE_ADMIN_AUTORECOVERYENABLED=${STORE_ADMIN_AUTORECOVERYENABLED:-true}
    ports:
      - ${PORT:-8081}:8080
    volumes:
      - $PWD/logs:/app/logs
      - ./application.properties:/app/config/application.properties
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"
