version: '3.9'

networks:
  ledger-sync-net:

services:
  ledger-sync-postgres:
    image: postgres:14.5
    shm_size: 16gb
    environment:
      - POSTGRES_USER=cardano-master
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=ledger_sync
      - POSTGRES_LOGGING=true
    ports:
      - "54333:5432"
    volumes:
      - $PWD/db-data/ledger-sync-postgres/:/var/lib/postgresql/data
    command: >
      postgres
        -c max_connections=500
        -c max_locks_per_transaction=256
        -c shared_buffers=12GB
        -c effective_cache_size=20GB
        -c maintenance_work_mem=4GB
        -c checkpoint_completion_target=0.9
        -c checkpoint_timeout=1h
        -c synchronous_commit=off
        -c wal_buffers=16MB
        -c default_statistics_target=500
        -c random_page_cost=1.1
        -c effective_io_concurrency=500
        -c work_mem=64GB
        -c min_wal_size=1GB
        -c max_wal_size=2GB
        -c max_parallel_workers_per_gather=4
        -c max_parallel_maintenance_workers=4
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "100"
    networks:
      - ledger-sync-net

  ledger-sync:
    image: cardanofoundation/ledger-sync:dev
    container_name: ledger-sync-${NETWORK:-mainnet}
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    #      target: ledger-sync
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://ledger-sync-postgres:5432/ledger_sync?currentSchema=cexplorer}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-cardano-master}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-dbpass}
      - SCHEMA=${SCHEMA:-cexplorer}
      - STORE_CARDANO_HOST=${STORE_CARDANO_HOST:-relays-new.cardano-mainnet.iohk.io}
      - STORE_CARDANO_PORT=${STORE_CARDANO_PORT:-3001}
      - STORE_CARDANO_PROTOCOL_MAGIC=${STORE_CARDANO_PROTOCOL_MAGIC:-764824073}
      - NETWORK=${NETWORK:-mainnet}
      - BLOCKS_BATCH_SIZE=${BLOCKS_BATCH_SIZE:-100}
      - COMMIT_THRESHOLD=${COMMIT_THRESHOLD:-3000}
      - MAXIMUM_POOL_SIZE=${MAXIMUM_POOL_SIZE:-48}
      - STORE_CARDANO_KEEP_ALIVE_INTERVAL=${STORE_CARDANO_KEEP_ALIVE_INTERVAL:-3000}
      - SCHEDULER_ENABLED=${SCHEDULER_ENABLED:-true}
      - HEALTH_CHECK_ENABLED=${HEALTH_CHECK_ENABLED:-true}
      - EVENT_TIME_THRESHOLD_IN_SECOND=${EVENT_TIME_THRESHOLD_IN_SECOND:-600}
      - BLOCK_TIME_CHECK_ENABLED=${BLOCK_TIME_CHECK_ENABLED:-true}
      - BLOCK_TIME_THRESHOLD_IN_SECOND=${BLOCK_TIME_THRESHOLD_IN_SECOND:-180}
    ports:
      - ${LEDGER_SYNC_MAIN_PORT:-8080}:8080
    volumes:
      - $PWD/ledger-sync-logs:/app/logs/

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"

    networks:
      - ledger-sync-net
  ledger-sync-aggregation:
    image: cardanofoundation/ledger-sync-aggregation:dev
    container_name: ledger-sync-aggregation-${NETWORK:-mainnet}
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    #      target: aggregation
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://ledger-sync-postgres:5432/ledger_sync?currentSchema=aggregation}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-cardano-master}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-dbpass}
      - STORE_CARDANO_HOST=${STORE_CARDANO_HOST:-relays-new.cardano-mainnet.iohk.io}
      - STORE_CARDANO_PORT=${STORE_CARDANO_PORT:-3001}
      - STORE_CARDANO_PROTOCOL_MAGIC=${STORE_CARDANO_PROTOCOL_MAGIC:-764824073}
      - NETWORK=${NETWORK:-mainnet}
      - HEALTH_CHECK_ENABLED=${HEALTH_CHECK_ENABLED:-true}
      - EVENT_TIME_THRESHOLD_IN_SECOND=${EVENT_TIME_THRESHOLD_IN_SECOND:-600}
      - BLOCK_TIME_CHECK_ENABLED=${BLOCK_TIME_CHECK_ENABLED:-true}
      - BLOCK_TIME_THRESHOLD_IN_SECOND=${BLOCK_TIME_THRESHOLD_IN_SECOND:-180}
    ports:
      - ${LEDGER_SYNC_AGGREGATION_PORT:-8081}:8080

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"

    networks:
      - ledger-sync-net