version: '3.9'

services:
  ledger-sync:
    image: cardanofoundation/cf-ledger-sync:0.1.2
    container_name: ledger-sync-${NETWORK:-mainnet}
    env_file:
      - .env
      - application.properties
    environment:
      - BLOCKS_BATCH_SIZE=${BLOCKS_BATCH_SIZE:-100}
      - COMMIT_THRESHOLD=${COMMIT_THRESHOLD:-3000}
      - MAXIMUM_POOL_SIZE=${MAXIMUM_POOL_SIZE:-48}
      - STORE_CARDANO_KEEP_ALIVE_INTERVAL=${STORE_CARDANO_KEEP_ALIVE_INTERVAL:-3000}
      - SCHEDULER_ENABLED=${SCHEDULER_ENABLED:-true}
      - HEALTH_CHECK_ENABLED=${HEALTH_CHECK_ENABLED:-true}
      - EVENT_TIME_THRESHOLD_IN_SECOND=${EVENT_TIME_THRESHOLD_IN_SECOND:-600}
      - BLOCK_TIME_CHECK_ENABLED=${BLOCK_TIME_CHECK_ENABLED:-true}
      - BLOCK_TIME_THRESHOLD_IN_SECOND=${BLOCK_TIME_THRESHOLD_IN_SECOND:-180}
    ports:
      - ${LEDGER_SYNC_MAIN_PORT:-8080}:8080
    volumes:
      - $PWD/logs:/app/logs/
      - ./application.properties:/app/config/application.properties
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"

