version: '3.9'

services:
  ledger-sync:
    image: cardanofoundation/ledger-sync:dev
    container_name: ledger-sync-${NETWORK:-mainnet}
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    #      target: ledger-sync
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://ledger-sync-postgres:5432/ledger_sync?currentSchema=ledger_sync}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-cardano-master}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-dbpass}
      - STORE_CARDANO_HOST=${STORE_CARDANO_HOST:-relays-new.cardano-mainnet.iohk.io}
      - STORE_CARDANO_PORT=${STORE_CARDANO_PORT:-3001}
      - STORE_CARDANO_PROTOCOLMAGIC=${STORE_CARDANO_PROTOCOLMAGIC:-764824073}
      - NETWORK=${NETWORK:-mainnet}
      - BLOCKS_BATCH_SIZE=${BLOCKS_BATCH_SIZE:-100}
      - COMMIT_THRESHOLD=${COMMIT_THRESHOLD:-3000}
      - MAXIMUM_POOL_SIZE=${MAXIMUM_POOL_SIZE:-48}
      - STORE_CARDANO_KEEP_ALIVE_INTERVAL=${STORE_CARDANO_KEEP_ALIVE_INTERVAL:-3000}
      - SCHEDULER_ENABLED=${SCHEDULER_ENABLED:-true}
      - HEALTH_CHECK_ENABLED=${HEALTH_CHECK_ENABLED:-true}
      - EVENT_TIME_THRESHOLD_IN_SECOND=${EVENT_TIME_THRESHOLD_IN_SECOND:-600}
      - BLOCK_TIME_CHECK_ENABLED=${BLOCK_TIME_CHECK_ENABLED:-true}
      - BLOCK_TIME_THRESHOLD_IN_SECOND=${BLOCK_TIME_THRESHOLD_IN_SECOND:-180}
    ports:
      - ${LEDGER_SYNC_MAIN_PORT:-8080}:8080
    volumes:
      - $PWD/logs:/app/logs/

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"

