version: '3.9'

services:
  ledger-sync-postgres:
    image: postgres:14.5
    shm_size: 16gb
    environment:
      - POSTGRES_USER=cardano-master
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=ledger_sync
      - POSTGRES_LOGGING=true
    ports:
      - "54333:5432"
    volumes:
      - $PWD/db-data/ledger-sync-postgres/:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U cardano-master -d ledger_sync'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "100"
