spring:
  banner:
    location: classpath:/banner.txt
  application:
    name: Ledger Sync Aggregation App

  flyway:
    locations:
      - classpath:db/store/{vendor}
      - classpath:db/account
    out-of-order: true
  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true

apiPrefix: /api/v1

logging:
  file:
    name: ./logs/ledger-sync-aggr.log

store:
  event-publisher-id: 1000
  auto-index-management: true
  cardano:
    keep-alive-interval: 3000
  account:
    enabled: true
    balance-aggregation-enabled: true
    history-cleanup-enabled: true
    # 3 months
    balance-cleanup-slot-count: 7889238
    api-enabled: true
    parallel-write: true
    write-thread-default-batch-size: 6000
    jooq-write-batch-size: 3000
    write-thread-count: 5
  executor:
    enable-parallel-processing: true
    block-processing-threads: 15
    event-processing-threads: 30
    blocks-batch-size: 100
    blocks-partition-size: 10
    use-virtual-thread-for-batch-processing: false
    use-virtual-thread-for-event-processing: true
