{{ if .Values.aggregation.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cf-ledger-sync.fullname" . }}{{ print "-aggregation" }}
  labels:
    {{- include "cf-ledger-sync-aggregation.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.aggregation.replicaCount }}
  selector:
    matchLabels:
      {{- include "cf-ledger-sync-aggregation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cf-ledger-sync-aggregation.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.tolerations }}
      tolerations:
        {{ with .Values.tolerations }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: "{{ .Chart.Name }}-aggregation"
          image: "{{ .Values.aggregation.image.repository }}:{{ .Values.aggregation.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.aggregation.image.pullPolicy }}
          env:
            - name: NETWORK
              value: {{ .Values.network | default "preprod" }}
            - name: DB_DIALECT
              value: {{ .Values.aggregation.dbDialect | default "org.hibernate.dialect.PostgreSQLDialect" }}
            - name: JAVA_OPTIONS
              value: "-Xms1G -Xmx12G"
            - name: JDK_JAVA_OPTIONS
              value: "-Xms1G -Xmx12G"

            {{ if .Values.useLocalCardanoNode }}
            - name: STORE_CARDANO_HOST
              value: "cardano-node"
            - name: STORE_CARDANO_PORT
              value: "3001"
              {{ if eq .Values.localCardanoNode.network "preview" }}
            - name: STORE_CARDANO_PROTOCOL_MAGIC
              value: "2"
              {{- else if eq .Values.localCardanoNode.network "preprod" }}
            - name: STORE_CARDANO_PROTOCOL_MAGIC
              value: "1"
              {{- else if eq .Values.localCardanoNode.network "mainnet" }}
            - name: STORE_CARDANO_PROTOCOL_MAGIC
              value: "764824073"
              {{- else if eq .Values.localCardanoNode.network "sanchonet" }}
            - name: STORE_CARDANO_PROTOCOL_MAGIC
              value: "4"
              {{- end }}
            {{- else }}
            - name: STORE_CARDANO_HOST
              value: {{ .Values.storeCardanoHost | default "preprod-node.world.dev.cardano.org" }}
            - name: STORE_CARDANO_PORT
              value: {{ .Values.storeCardanoPort | default "30000" | quote }}
            - name: STORE_CARDANO_PROTOCOL_MAGIC
              value: {{ .Values.storeCardanoProtocolMagic | default "1" | quote }}
            {{- end }}

            ## Postgres
            {{- with .Values.aggregation.postgres }}
            - name: POSTGRES_HOST
              {{- if .host }}
              value: {{ .host }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .hostKey }}
              {{- end }}
            - name: POSTGRES_PORT
              {{- if .port }}
              value: {{ .port | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .portKey }}
              {{- end }}
            - name: POSTGRES_DB
              {{- if .db }}
              value: {{ .db }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .dbKey }}
              {{- end }}
            - name: SCHEMA
              value: {{ .dbSchema | default "aggregation" }}
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?currentSchema=$(SCHEMA)
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .userKey }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .passwordKey }}
            {{- end }}

            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: {{ .Values.aggregation.db.maximum_pool_size | default 50 | quote }}

            - name: HEALTH_CHECK_ENABLED
              value: "true"
            - name: EVENT_TIME_THRESHOLD_IN_SECOND
              value: "600"
            - name: BLOCK_TIME_CHECK_ENABLED
              value: "true"
            - name: BLOCK_TIME_THRESHOLD_IN_SECOND
              value: "180"

            - name: STORE_ACCOUNT_HISTORYCLEANUPENABLED
              value: {{ .Values.aggregation.store.account.history_cleanup_enabled | default "false" | quote }}
            - name: STORE_ACCOUNT_INITIALBALANCESNAPSHOTBLOCK
              value: "0"
            - name: STORE_ACCOUNT_BALANCECALCJOBBATCHSIZE
              value: "500"
            - name: STORE_ACCOUNT_BALANCECALCJOBPARTITIONSIZE
              value: "5"
            - name: STORE_ADMIN_HEALTHCHECKINTERVAL
              value: "120"
            - name: STORE_ADMIN_AUTORECOVERYENABLED
              value: "true"
            - name: STORE_ADMIN_APIENABLED
              value: "true"

#            - name: STORE_EXECUTOR_BLOCKS_BATCH_SIZE
#              value: {{ .Values.aggregation.store.executor.blocks_batch_size | default 100 | quote }}
#            - name: STORE_EXECUTOR_BLOCKS_PARTITION_SIZE
#              value: {{ .Values.aggregation.store.executor.blocks_partition_size | default 10 | quote }}
#
#            - name: STORE_EXECUTOR_BLOCK_PROCESSING_THREADS
#              value: {{ .Values.aggregation.store.executor.block_processing_threads | default 15 | quote }}
#            - name: STORE_EXECUTOR_EVENT_PROCESSING_THREADS
#              value: {{ .Values.aggregation.store.executor.event_processing_threads | default 30 | quote }}

            - name: STORE_EXECUTOR_USE_VIRTUAL_THREAD_FOR_BATCH_PROCESSING
              value: {{ .Values.aggregation.store.executor.use_virtual_thread_for_batch_processing | default "true" | quote }}
            - name: STORE_EXECUTOR_USE_VIRTUAL_THREAD_FOR_EVENT_PROCESSING
              value: {{ .Values.aggregation.store.executor.use_virtual_thread_for_event_processing | default "true" | quote }}
            - name: STORE_EXECUTOR_ENABLE_PARALLEL_PROCESSING
              value: {{ .Values.aggregation.store.executor.enable_parallel_processing | default "true" | quote }}

            - name: HIKARI_MINIMUM_IDLE
              value: {{ .Values.indexer.hikari.minimumIdle | default "10" | quote }}
            - name: HIKARI_MAXIMUM_POOL_SIZE
              value: {{ .Values.indexer.hikari.maximumPoolSize | default "48" | quote }}
            - name: HIKARI_CONNECTION_TIMEOUT
              value: {{ .Values.indexer.hikari.connectionTimeout | default "50000" | quote }}
            - name: HIKARI_IDLE_TIMEOUT
              value: {{ .Values.indexer.hikari.idleTimeout | default "300000" | quote }}
            - name: HIKARI_MAX_LIFETIME
              value: {{ .Values.indexer.hikari.maxLifetime | default "900000" | quote }}
            - name: HIKARI_AUTO_COMMIT
              value: {{ .Values.indexer.hikari.autoCommit | default "true" | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.aggregation.resources | nindent 12 }}
  strategy:
    type: Recreate
{{ end }}
