{{ if .Values.indexer.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cf-ledger-sync.fullname" . }}{{ print "-aggregation" }}
  labels:
    {{- include "cf-ledger-sync-aggregation.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.aggregation.replicaCount }}
  selector:
    matchLabels:
      {{- include "cf-ledger-sync-aggregation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cf-ledger-sync-aggregation.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: "{{ .Chart.Name }}-aggregation"
          image: "{{ .Values.aggregation.image.repository }}:{{ .Values.aggregation.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.aggregation.image.pullPolicy }}
          env:
            - name: NETWORK
              value: {{ .Values.network | default "preprod" }}
            - name: DB_DIALECT
              value: {{ .Values.aggregation.dbDialect | default "org.hibernate.dialect.PostgreSQLDialect" }}

            {{ if .Values.useLocalCardanoNode }}
            - name: STORE_CARDANO_HOST
              value: "cardano-node"
            - name: STORE_CARDANO_PORT
              value: "3001"
              {{ if eq .Values.localCardanoNode.network "preview" }}
            - name: STORE_CARDANO_PROTOCOL_MAGIC
              value: "2"
              {{- else if eq .Values.localCardanoNode.network "preprod" }}
            - name: STORE_CARDANO_PROTOCOL_MAGIC
              value: "1"
              {{- else if eq .Values.localCardanoNode.network "mainnet" }}
            - name: STORE_CARDANO_PROTOCOL_MAGIC
              value: "764824073"
              {{- else if eq .Values.localCardanoNode.network "sanchonet" }}
            - name: STORE_CARDANO_PROTOCOL_MAGIC
              value: "4"
              {{- end }}
            {{- else }}
            - name: STORE_CARDANO_HOST
              value: {{ .Values.storeCardanoHost | default "preprod-node.world.dev.cardano.org" }}
            - name: STORE_CARDANO_PORT
              value: {{ .Values.storeCardanoPort | default "30000" | quote }}
            - name: STORE_CARDANO_PROTOCOL_MAGIC
              value: {{ .Values.storeCardanoProtocolMagic | default "1" | quote }}
            {{- end }}

            ## Postgres
            {{- with .Values.aggregation.postgres }}
            - name: POSTGRES_HOST
              {{- if .host }}
              value: {{ .host }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .hostKey }}
              {{- end }}
            - name: POSTGRES_PORT
              {{- if .port }}
              value: {{ .port | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .portKey }}
              {{- end }}
            - name: POSTGRES_DB
              {{- if .db }}
              value: {{ .db }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .dbKey }}
              {{- end }}
            - name: SCHEMA
              value: {{ .dbSchema | default "aggregation" }}
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?currentSchema=$(SCHEMA)
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .userKey }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .passwordKey }}
            {{- end }}

            - name: HEALTH_CHECK_ENABLED
              value: "true"
            - name: EVENT_TIME_THRESHOLD_IN_SECOND
              value: "600"
            - name: BLOCK_TIME_CHECK_ENABLED
              value: "true"
            - name: BLOCK_TIME_THRESHOLD_IN_SECOND
              value: "180"

            - name: STORE_ACCOUNT_HISTORYCLEANUPENABLED
              value: {{ .Values.aggregation.store.account.history_cleanup_enabled | quote }}
            - name: STORE_ACCOUNT_INITIALBALANCESNAPSHOTBLOCK
              value: "0"
            - name: STORE_ACCOUNT_BALANCECALCJOBBATCHSIZE
              value: "500"
            - name: STORE_ACCOUNT_BALANCECALCJOBPARTITIONSIZE
              value: "5"
            - name: STORE_ADMIN_HEALTHCHECKINTERVAL
              value: "120"
            - name: STORE_ADMIN_AUTORECOVERYENABLED
              value: "true"
            - name: STORE_EXECUTOR_BLOCKPROCESSINGTHREADS
              value: {{ .Values.aggregation.store.executor.block_processing_threads | default 15 | quote }}
            - name: STORE_EXECUTOR_USEVIRTUALTHREADFORBATCHPROCESSING
              value: {{ .Values.aggregation.store.executor.use_virtual_thread_for_batch_processing | default "false" | quote }}
            - name: STORE_EXECUTOR_ENABLEPARALLELPROCESSING
              value: {{ .Values.aggregation.store.executor.enable_parallel_processing | default "true" | quote }}

          resources:
            {{- toYaml .Values.aggregation.resources | nindent 12 }}
  strategy:
    type: Recreate
{{ end }}
