name: Clean, Build

on:
  push:
    branches:
      - main
      - develop
      - store_int
  pull_request:
    branches:
      - main
      - develop
      - store_int

jobs:
  commit-build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'liberica'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -PskipSigning=true --stacktrace
