name: Deploy to GitHub Pages

on:
  push:
    tags:
      - 'rel-docs*'

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: "./docs/yarn.lock"

      - name: Install dependencies
        run: |
          cd docs
          yarn install --frozen-lockfile
      - name: Build website
        run: |
          cd docs
          yarn export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./docs/out
          #cname: example.com
