name: run Android tests in github runner

on: push

jobs:
  run-ios-tests:
    runs-on: macos-latest

    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: pull the project in to the runner
        uses: actions/checkout@v3

      - name: setup appium
        run: npm install @appium/doctor --location=global

      - name: setup appium
        run: appium-doctor --android

      - name: setup appium
        run: |
          npm i -g appium@next
          appium driver install uiautomator2
          appium &>/dev/null &

      - name: run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
            api-level: 29
            script: ./gradlew run


      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: build/allure-results
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

#      - name: Post the link to the report
#        if: always()
#        uses: Sibz/github-status-action@v1
#        with:
#          authToken: ${{secrets.GITHUB_TOKEN}}
#          context: 'Test report'
#          state: 'success'
#          sha: ${{ github.event.pull_request.head.sha }}
#          target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
