name: run ios tests in github runner

on: push

jobs:
  run-ios-tests:
    runs-on: macos-latest

    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: pull the project in to the runner
        uses: actions/checkout@v3