name: Publish package to the Maven Central Repository
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'liberica'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Decode GPG Key
        run: |
          mkdir -p ~/.gradle/
          echo "${{secrets.MAVEN_CENTRAL_GPG_KEY_BASE64}}" > ~/.gradle/secring.gpg.b64
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg
      - name: Publish package
        run: |
          ./gradlew publish \
            "-Psigning.keyId=${{ secrets.MAVEN_CENTRAL_GPG_KEY_ID }}" \
            "-Psigning.password=${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}" \
            "-Psigning.secretKeyRingFile=${HOME}/.gradle/secring.gpg" \
            --warn --stacktrace
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}
