name: Manual Snapshot Push to SNAPSHOT repo

on:
  workflow_dispatch:

jobs:
  commit-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'liberica'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build -PskipSigning=true --stacktrace
      - name: Publish package to SNAPSHOT repository
        run: ./gradlew publish -PskipSigning=true --warn --stacktrace
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_OSSRH_TOKEN }}
