name: Run explorer FE testcases
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-web-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run the FE tests
        run: |
          gradle clean test