name: Run Explorer FE testcases
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-web-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Run the FE tests
        run: |
          gradle clean test