name: Run Explorer FE testcases
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-web-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        java-version: |
          8
          11
          17

      - name: Run the FE tests
        run: |
          gradle clean test