on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
            java-version: 17
            distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run test with Gradle Wrapper
        run: ./gradlew test

      - name: Run allure report
        run: ./gradlew allureReport
